// Application error code labels. Prefix: ERROR_CODE_

export const ERROR_CODE_VALIDATION = 'VALIDATION_ERROR';
export const ERROR_CODE_UNAUTHORIZED = 'UNAUTHORIZED';
export const ERROR_CODE_FORBIDDEN = 'FORBIDDEN';
export const ERROR_CODE_NOT_FOUND = 'NOT_FOUND';
export const ERROR_CODE_CONFLICT = 'CONFLICT';
export const ERROR_CODE_INTERNAL = 'INTERNAL_ERROR';
export const ERROR_CODE_DB = 'DATABASE_ERROR';
export const ERROR_CODE_ROUTE = 'ROUTE_ERROR';
export const ERROR_CODE_API = 'API_ERROR';

export const ERROR_CODE = {
  VALIDATION: ERROR_CODE_VALIDATION,
  UNAUTHORIZED: ERROR_CODE_UNAUTHORIZED,
  FORBIDDEN: ERROR_CODE_FORBIDDEN,
  NOT_FOUND: ERROR_CODE_NOT_FOUND,
  CONFLICT: ERROR_CODE_CONFLICT,
  INTERNAL_ERROR: ERROR_CODE_INTERNAL,
  DATABASE_ERROR: ERROR_CODE_DB,
  ROUTE_ERROR: ERROR_CODE_ROUTE,
  API_ERROR: ERROR_CODE_API,
} as const;
