// HTTP status code labels. Prefix: STATUS_CODE_

export const STATUS_CODE_OK = 200;
export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_NO_CONTENT = 204;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_UNAUTHORIZED = 401;
export const STATUS_CODE_FORBIDDEN = 403;
export const STATUS_CODE_NOT_FOUND = 404;
export const STATUS_CODE_CONFLICT = 409;
export const STATUS_CODE_UNPROCESSABLE_ENTITY = 422;
export const STATUS_CODE_TOO_MANY_REQUESTS = 429;
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
export const STATUS_CODE_SERVICE_UNAVAILABLE = 503;

export const STATUS_CODE = {
  OK: STATUS_CODE_OK,
  CREATED: STATUS_CODE_CREATED,
  NO_CONTENT: STATUS_CODE_NO_CONTENT,
  BAD_REQUEST: STATUS_CODE_BAD_REQUEST,
  UNAUTHORIZED: STATUS_CODE_UNAUTHORIZED,
  FORBIDDEN: STATUS_CODE_FORBIDDEN,
  NOT_FOUND: STATUS_CODE_NOT_FOUND,
  CONFLICT: STATUS_CODE_CONFLICT,
  UNPROCESSABLE_ENTITY: STATUS_CODE_UNPROCESSABLE_ENTITY,
  TOO_MANY_REQUESTS: STATUS_CODE_TOO_MANY_REQUESTS,
  INTERNAL_SERVER_ERROR: STATUS_CODE_INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE: STATUS_CODE_SERVICE_UNAVAILABLE,
} as const;
